/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Report.GeraRelatorio;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Deyvid
 */
public class TelaListagem extends javax.swing.JInternalFrame {
    
    String arg;
    String situacao;
    int ativo = 1;
    int inativo = 0;

    /**
     * Creates new form TelaListagem
     */
    public TelaListagem() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgListagem = new javax.swing.ButtonGroup();
        jRTodos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRAtivo = new javax.swing.JRadioButton();
        jRInativo = new javax.swing.JRadioButton();
        btnImprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        bgListagem.add(jRTodos);
        jRTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRTodos.setText("Todos");
        jRTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTodosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Listagem de Clientes: Ativos ou Inativos");

        bgListagem.add(jRAtivo);
        jRAtivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRAtivo.setText("Ativos");
        jRAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAtivoActionPerformed(evt);
            }
        });

        bgListagem.add(jRInativo);
        jRInativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRInativo.setText("Inativos");
        jRInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRInativoActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/print_icon.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jRTodos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRInativo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTodos)
                    .addComponent(jRAtivo)
                    .addComponent(jRInativo))
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        jRTodos.setSelected(true);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        
        String arg = "";
        String  ativo = "1";
        String inativo = "0";
        
        if(jRAtivo.isSelected()){
            arg = ativo;
        }
        if(jRInativo.isSelected()){
            arg = inativo;
        }
        if(jRTodos.isSelected()){
            arg = "ativo or situacao = inativo";
        }
        
        GeraRelatorio relatorio = new GeraRelatorio();
        
        try {
            relatorio.listagem("C:/Users/Deyvid/Documents/FIC/2022.1/Programação II/ProjetoCrudCadastro/"
                    + "src/Report/listagem.jasper", arg);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Eroro ao gera relatório: "+ erro);
            
        }
        
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void jRAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAtivoActionPerformed
        // TODO add your handling code here:
        String arg = "";
        String  ativo = "1";
        
        if(jRAtivo.isSelected()){
            arg = ativo;
        }
    }//GEN-LAST:event_jRAtivoActionPerformed

    private void jRTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTodosActionPerformed
        // TODO add your handling code here:
        String arg = "";
        String  ativo = "1";
        String inativo = "0";
        
        if(jRTodos.isSelected()){
            arg = "ativo or situacao = inativo";
        }
    }//GEN-LAST:event_jRTodosActionPerformed

    private void jRInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRInativoActionPerformed
        // TODO add your handling code here:
        String arg = "";
        String  inativo = "0";
        
        if(jRInativo.isSelected()){
            arg = inativo;
        }
    }//GEN-LAST:event_jRInativoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgListagem;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRAtivo;
    private javax.swing.JRadioButton jRInativo;
    private javax.swing.JRadioButton jRTodos;
    // End of variables declaration//GEN-END:variables
}
